### ISSUE TITLE
Task 2 (Explaining white-box models)

### ISSUE THREAD

**Issue by hugzito** [Steinar-Slette/AF_mandatory#4]
### Task 2.1
- [ ] Explain logistic regression model
- [ ] Which features are deemed most relevant?
- [ ] How does the result fit with our intuition?

### Task 2.2
- [ ] Pick one datapoint in test-set. 
- [ ] Find counterfactual datapoint.
- [ ] Describe the difference in terms of model.
